### PR TITLE
Promise.prototype.finally

### PR DESCRIPTION
**Pull request by rainydio**
Implemented it accoding to http://www.2ality.com/2014/10/es6-promises-api.html

It isn't in the spec though

Also see:
https://esdiscuss.org/topic/proposal-promise-prototype-finally
https://esdiscuss.org/topic/why-the-ecmascript-2015-promises-don-t-have-finally-methods
https://github.com/domenic/promises-unwrapping/issues/18
https://github.com/getify/You-Dont-Know-JS/blob/master/async%20&%20performance/ch3.md#finally

Someone arguing against it:
https://github.com/domenic/promises-unwrapping/issues/18#issuecomment-63504016

### CODE REVIEW

**Comment by taylorhakes** [comment]
I really like `finally`, but unfortunately this library is just a strict polyfill. I don't want to have any other functions that are not in the spec or about to be in the spec. `finally` is not even a proposal right now. Feel free to fork this repo to add finally or extend this promise to add `finally`.

I would love to see a proposal for `finally` and [filtered catch](http://bluebirdjs.com/docs/api/catch.html#filtered-catch).

**Comment by rainydio** [comment]
Okay. I can totally understand this.

**Comment by twhitbeck** [comment]
Promise.prototype.finally` is at stage3, can we reopen this?

**Comment by xiaoping0x** [comment]
Really need `finally`, so I switched to https://github.com/stefanpenner/es6-promise

**Pull request closed without merging**
