### PR TITLE
Add Promise.prototype.finally

### PR DESCRIPTION
**Pull request by Andarist**
This method was added as part of es2018

### CODE REVIEW

**Comment by taylorhakes** [comment]
@Andarist Thanks for doing this, but the code does not match the spec. .finally return value should not be used unless it throws an error.

**Comment by taylorhakes** [comment]
Here is more info https://github.com/tc39/proposal-promise-finally/blob/master/README.md . I will only merge a .finally PR if it has tests as well

**Comment by Andarist** [comment]
Fair enough, I was under impression that this works differently - didnt even read the spec too much as the feature seamed to be straightforward. I was so wrong 🙈  and truth to be told the spec behaviour is really weird to me, the idea that promise created returned from finally carry with it result of the "previous" promise seems bizarre.

I'll look later if I can plug in the tests and implement this, but can't promise (😉) that I'll actually decide to do it.

Thanks for noticing my ignorance and not merging this.

**Comment by taylorhakes** [comment]
No problem. Never expect anyone to additional work (especially for free). I am happy to work on it next week if you don’t have time or don’t want to. Let me know.

**Comment by Andarist** [comment]
I've looked quickly through the source code and I think I'm going to give it a pass this time. I can look into preparing test setup though, will let u know later if I manage to do this.

**Pull request closed without merging**
