### PR TITLE
Catch errors when we throw em

### PR DESCRIPTION
**Pull request by anthony-dandrea**
I've been getting uncaught errors on this line: `if (typeof fn !== 'function') throw new TypeError('not a function');` in IE. We should catch any errors when we throw them.

### CODE REVIEW

**Comment by taylorhakes** [comment]
@anthony-dandrea I am confused by this pull request. Why do we need to catch errors? The code is meant to throw an error.

**Comment by anthony-dandrea** [comment]
Apologies for not being more detailed originally. So without catching these thrown errors all script execution seems to break and cease. I think it would be more graceful to just throw, catch, and log these errors in the console rather than having the rest of the functionality of the site seize up.

Before my change:
bad
After my change:
good

Worth noting I am testing in IE10.

**Comment by taylorhakes** [comment]
Are you not passing a function? Meaning, is the error correct or are you seeing the library not working at all in general?

**Comment by anthony-dandrea** [comment]
I was initializing something in a silly way. Sorry for delayed responsive. Debugging in IE is a struggle.

**Pull request closed without merging**
