### PR TITLE
Use queueMicrotask when available. Fix #109

### LINKED ISSUE #109: Use window.queueMicrotask where available
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask

Unlike many others, this is standard api.
Contrary to setImmediate, it cannot be cancelled. Also it's the ideal queue for promises: Promise callbacks are indeed microtasks.

### PR DESCRIPTION
**Pull request by kapouer**

### CODE REVIEW

**Comment by taylorhakes** [comment]
Thanks for creating this. Looks like travis CI changed. I updated master to work. Please rebase and the tests should pass.

**Comment by taylorhakes** [comment]
Looks like Closure compiler does not recognize `queueMicrotask`. We need to create an extern file to make the compiling pass.

https://developers.google.com/closure/compiler/docs/api-tutorial3#howto-app

Let's create a file `src/closure_compiler_externs.js` with the following content

```js
// Closure Compiler extern definitions
function queueMicrotask(fn) {}
```

That should make the test pass. If not, we just need to add the file as an extern definition to the closure command in package.json.

```
"closure": "google-closure-compiler --js=src/*.js --checks_only --module_resolution=node --compilation_level=ADVANCED --externs src/closure_compiler_externs.js",
```

**Comment by kapouer** [comment]
Not sure this is the right approach, since `queueMicrotask`, `setImmediate` are methods of the window object, why not do `window.queueMicrotask`, ....

**Comment by taylorhakes** [comment]
This library needs to support Node and webworkers, which don’t have a
window object. queueMicrotask is available in web workers.

**Comment by taylorhakes** [comment]
Closing due to inactivity

**Pull request closed without merging**
