### PR TITLE
Chrome reports the minified gzipped size as 1.8KB

### PR DESCRIPTION
**Pull request by rosenfeld**

### CODE REVIEW

**Comment by Andarist** [comment]
@rosenfeld @taylorhakes  That's quite weird, I've just checked on my machine with `gzip -c promise.min.js | wc -c` and its giving me result of 1019 bytes (so still under 1kb!) for the latest master version (for the fresh built, whats actually on the master now yields 1022 bytes).

**Comment by rosenfeld** [comment]
This is how I measured it:

image

**Comment by Andarist** [comment]
screen shot 2017-08-07 at 20 25 22
1.8KB in the Network is shown in the Network tab because its a sum of Content-Length (1007 bytes) + Headers sent with the response (826 bytes). This value should not be treated as the size of the library.

**Comment by rosenfeld** [comment]
Oh, sorry, I didn't notice the headers size was that big. That's right, then. Sorry for the confusion. Will keep that in mind when evaluating the size of libraries from now on. Thanks for the explanation.

**Comment by Andarist** [comment]
No problem :) I was confused a little bit about the Size from Network panel myself, had to figure out why it was different than actual content ;p also the second number given (2.6KB) is the size of the file after decoding (so without headers...). Kinda confusing stuff.

**Comment by rosenfeld** [comment]
I also didn't know that 2.6KB wouldn't take into account the headers. This is counter intuitive :) But anyway, good to know :)

**Pull request merged**
